apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app1
  template:
    metadata:
      labels:
        app: demo-app1
    spec:
      containers:
      - name: demo-app1
        image: rajeshnimmana/dockerbuild:vWeatherapp20250925093122
        ports:
        - containerPort: 5001
