apiVersion: v1
kind: Service
metadata:
  name: demo-app1-service
spec:
  selector:
    app: demo-app1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort

  
