apiVersion: v1
kind: Service
metadata:
  name: demo-app1-service
spec:
  selector:
    app: demo-app1
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30009
  type: NodePort

  
