apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
 # namespace: dev    # <-- Namespace goes here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: latest_nginx
        ports:
        - containerPort: 80
