apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
 # namespace: dev   # <-- Add this if your Deployment is in the 'dev' namespace
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8082
  type: NodePort
