apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  selector:
    matchLabels:
      app: guestbook-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: rajeshnimmana/dockerbuild:latest_nodjs
          name: guestbook-ui
          ports:
            - containerPort: 80
