apiVersion: v1
kind: Service
metadata:
  name: prod-service
spec:
  selector:
    app: prod
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30010
  type: NodePort
